# Generated by Django 4.2 on 2024-09-29 22:49

import ckeditor.fields
import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
                ('color', colorful.fields.RGBColorField()),
                ('link', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Salones',
            },
        ),
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_category', to='api.categoryitem')),
            ],
            options={
                'verbose_name_plural': 'Categorias de Actividades',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', ckeditor.fields.RichTextField()),
                ('dress_code', models.CharField(choices=[('n/a', 'N/A'), ('formal', 'Formal'), ('casual', 'Casual')], max_length=50, verbose_name='Código de vestir')),
                ('academic_program_url', models.URLField(blank=True, max_length=500, verbose_name='Url Programa Académico')),
                ('inscription_url', models.URLField(blank=True, max_length=500, verbose_name='Url Inscripción')),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
                ('month', models.CharField(blank=True, default='', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='api.activitycategory')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salon')),
            ],
            options={
                'verbose_name_plural': 'Actividades',
                'ordering': ['start_date', 'ordering'],
            },
        ),
    ]
