# Generated by Django 4.2 on 2024-10-02 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('doctor', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='')),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='api.actividad')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
    ]
