name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:  
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH with Deploy Key
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H femecogvirtual.com >> ~/.ssh/known_hosts
      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/id_rsa django@femecogvirtual.com  << 'EOF'
          cd appfemecog
          git pull origin main
          EOF
